### ISSUE TITLE
Custom galileo build

### ISSUE THREAD

**Issue by ddmendes** [ddmendes/R3V-Remote3DViewer#5]
Follow http://www.malinov.com/Home/sergey-s-blog/intelgalileo-buildinglinuximage

**Comment by dev-har** [comment]
interesting link: http://www.krminc.com/gt-m-intel-galileo/

**Comment by dev-har** [comment]
Intel developer guide for galileo: http://alextgalileo.altervista.org/galileo-linux-images.html

**Comment by ddmendes** [comment]
Some guides to build yocto for galileo:
- http://architechboards-galileo.readthedocs.org/en/latest/tools.html

**Comment by ddmendes** [comment]
Backup sd image:
- https://github.com/IntelOpenDesign/MakerNode/wiki/SD-card:-backup-and-duplication

**Comment by ddmendes** [comment]
Using alext devtools yocto build for galileo:
- https://communities.intel.com/thread/49601?start=45&tstart=0
