### ISSUE TITLE
resolv.conf cleared at boot

### ISSUE THREAD

**Issue by ddmendes** [ddmendes/R3V-Remote3DViewer#6]

**Comment by ddmendes** [comment]
[SOLUTION] - Create a script to run during boot that populate resolv.conf nameservers.

- Create the right resolv.conf at /etc/conf/resolv.conf
- Create [this](https://github.com/ddmendes/R3V-Remote3DViewer/conf/resolvconf.sh) file at /etc/init.d/
- Gives right permission to the script: `# chmod 755 /etc/init.d/resolvconf.sh`
- Add the script to rc scripts: `# update-rc.d /etc/init.d/resolvconf.sh defaults`

Any problems, refer to https://www.debian-administration.org/article/28/Making_scripts_run_at_boot_time_with_Debian

**Comment by dev-har** [comment]
Connman solution

-- https://communities.intel.com/thread/49348
